<?xml version="1.0"?>
<package format="3">
  <name>ocp_solver</name>
  <version>0.0.0</version>
  <description>ocp_solver</description>

  <maintainer email="t-hiraoka@jsk.imi.i.u-tokyo.ac.jp">Takuma-Hiraoka</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ocs2_robotic_tools</depend>
  <depend>ocs2_core</depend>
  <depend>ocs2_pinocchio_interface</depend>
  <depend>pinocchio</depend>
  <depend>ocs2_oc</depend>
  <depend>ocs2_mpc</depend>
  <depend>ocs2_sqp</depend>
  <depend>pinocchio_model_builder</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
